#!/usr/bin/env php
<?php
/**
 * Test console bootstrap file.
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');
defined('YII_APP_BASE_PATH') or define('YII_APP_BASE_PATH', __DIR__ . '/../../');

require(__DIR__ . '/../../vendor/autoload.php');
require(__DIR__ . '/../../vendor/yiisoft/yii2/Yii.php');

$config = yii\helpers\ArrayHelper::merge(
    require(YII_APP_BASE_PATH . '/humhub/config/common.php'),
    require(YII_APP_BASE_PATH . '/humhub/config/console.php'),
    require(__DIR__ . '/tests/config.php')
);

$application = new \humhub\components\console\Application($config);
$application->params['installed'] = false;
$exitCode = $application->run();
exit($exitCode);
