<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allow others to create new issue on your profile page' => '',
    'Allow others to edit issue on your profile page' => '',
    'Allow to view all documents and their all issues, with download files' => 'Позволяет просматривать документы, их задачи и скачивать файлы',
    'Allow to view all documents and their all issues, without access to files' => 'Позволяет просматривать документы, их задачи, без скачивания файлы',
    'View all documents and files' => 'Просмотр всех документов и файлов',
    'Add documents' => 'Добавлять документы',
    'Add receivers to documents' => 'Добавлять получателей к документам',
    'Allow to added new receivers users to available documents' => 'Даёт права на добавление новых получателей к доступным документам',
    'Allow to upload new documents and to add information on it' => 'Даёт права на загрузку новых документов и описание его',
    'Allows the user to create issue' => 'Позволяет пользователю создавать задачу',
    'Allows the user to edit issue' => 'Позволяет пользователю изменять задачу',
    'Create issue' => 'Создать задачу',
    'Edit issue' => 'Изменить задачу',
    'View all documents' => 'Просмотр всех документов',
];
