<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Validity period' => 'Срок действия',
    '<strong>Designate</strong> tag to issue' => '<strong>Назначить</strong> номенклатуру к задаче',
    'Add' => 'Добавить',
    'Add Subtask' => 'Добавить подзадачу',
    'Adopted' => 'Принято',
    'Adopted at' => 'Принято в',
    'Assigned Users' => 'Ответственные',
    'Assigned at' => 'Назначен в',
    'Assignee' => 'Ответственные',
    'Background Color' => 'Цвет фона',
    'Calendar' => 'Календарь',
    'Create Tag' => 'Создать номенклатуру',
    'Date' => 'Дата',
    'Deadline' => 'Крайний срок',
    'Deadline Date' => 'Дата, крайний срок',
    'Deadline Time' => 'Время, крайний срок',
    'Description' => 'Описание',
    'Designate tag' => 'Назначить номенклатуру',
    'Done' => 'Выполнено',
    'Finish issue' => 'Завершить задачу',
    'Finished at' => 'Закончено в',
    'From this time recommended begin to start work' => 'Рекомендуемое время начала работ',
    'Has not deadline' => 'Без крайнего срока',
    'More details, please...' => 'Подробнее, пожалуйста...',
    'Must be completed by' => 'Срок до',
    'Name' => 'Наименование',
    'New issue' => 'Новая задача',
    'No open issues...' => 'Нет открытых задач...',
    'Notify assignors' => 'Оповестить ответственных',
    'Owner' => 'Владелец',
    'Priority' => 'Приоритет',
    'Save' => 'Сохранить',
    'Select a space in which the new issue will be added. If nothing is selected, the task will be attached to your profile.' => 'Выберите пространство, в которое будет добавлена новая задача. Если ничего не выбрано, то задача будет присоединена к вашему профилю.',
    'Select assignees' => 'Выберите ответственных',
    'Started Date' => 'Дата начала',
    'Started Time' => 'Время начала',
    'Started at' => 'Начато в',
    'Status' => 'Статус',
    'Tags' => 'Номенклатура',
    'Text Color' => 'Цвет текста',
    'The planned time by which you should end work.' => 'Планируемое время окончания работ.',
    'This issue has subtasks' => 'Имеет подзадачи',
    'This issue is subtask for the issue' => 'Является подзадачей к этой задаче',
    'This list of personal tags. It is can be a tag, a milestone, label or other that you can mark a issue. This tags visible only for you.' => 'Это список персональных ярлыков. Это может быть номенклатурой, этапом, закладкой или всем, чем вы можете отметить задачу. Эти отметки видны только вам.',
    'Timeline' => 'Временная шкала',
    'Title' => 'Наименование',
    'Visibility' => 'Отображение',
    'What is to do?' => 'Что сделать?',
    'constantly' => 'постоянно',
    'from' => 'от',
    'to' => 'до',
    '{userName} assigned you to the issue {issue}.' => '{userName} назначил вас ответственным по задаче {issue}.',
    '{userName} changed the issue {issue} wherever you are assigned.' => '{userName} изменил задачу {issue}, по которой вы ответственны.',
];
