<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Creator' => 'Создатель',
    '<strong>Describe</strong> new issue' => '<strong>Опишите</strong> новую задачу',
    '<strong>Edit</strong> issue' => '<strong>Изменить</strong> задачу',
    'Adopted' => 'Принято',
    'Adopted in work' => 'Принято в работу',
    'Assigned Users' => 'Ответственные',
    'Assignee' => 'Ответственные',
    'Date' => 'Дата',
    'Deadline' => 'Крайний срок',
    'Deadline Date' => 'Дата, крайний срок',
    'Deadline Time' => 'Время, крайний срок',
    'Description' => 'Описание',
    'Done' => 'Выполнено',
    'Has not deadline' => 'Без крайнего срока',
    'More details, please...' => 'Подробнее, пожалуйста...',
    'Must be completed by' => 'Должно быть выполнено до',
    'New issue' => 'Новая задача',
    'No open issues...' => 'Нет открытых задач...',
    'Performed' => 'Завершены',
    'Save' => 'Сохранить',
    'Status' => 'Статус',
    'Title' => 'Наименование',
    'Visibility' => 'Видимость',
    'What is to do?' => 'Что сделать?',
];
