<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Critical' => 'Critique',
    'Draft' => 'Brouillon',
    'Finished' => 'Terminé',
    'For all' => 'Pour tous',
    'For space' => 'Pour projet',
    'In work' => 'En travail',
    'Minor' => 'Mineur',
    'Normal' => 'Normal',
    'Private' => 'Privé',
    'Refer' => 'Référence',
    'Serious' => 'Sérieux',
    'Subtask' => 'Sous-tâche',
    'Urgent' => 'Urgent',
];
