<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add documents' => '',
    'Add receivers to documents' => '',
    'Allow others to create new issue on your profile page' => '',
    'Allow others to edit issue on your profile page' => '',
    'Allow to added new receivers users to available documents' => '',
    'Allow to upload new documents and to add information on it' => '',
    'Allow to view all documents and their all issues' => '',
    'Allows the user to create issue' => '',
    'Allows the user to edit issue' => '',
    'Create issue' => '',
    'Edit issue' => '',
    'View all documents' => '',
];
