<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Designate</strong> tag to issue' => '<strong>Désigner</strong> tag à la tâche',
    'Add' => 'Ajouter',
    'Add Subtask' => 'Ajouter sous-tâche',
    'Adopted' => 'Adopté',
    'Adopted at' => 'Adopté le',
    'Are you sure you want to delete this item?' => 'Êtes-vous sûr de vouloir effacer cette tâche ?',
    'Assigned Users' => 'Utilisateurs assignés',
    'Assigned at' => 'Assigné le',
    'Assignee' => 'Assigné à',
    'Background Color' => 'Couleur de fond',
    'Calendar' => 'Calendrier',
    'Create Tag' => 'Créer Tag',
    'Date' => 'Date',
    'Deadline' => 'Limite',
    'Deadline Date' => 'Date limite',
    'Deadline Time' => 'Heure limite',
    'Description' => 'Description',
    'Designate tag' => 'Tag description',
    'Done' => 'Terminé',
    'Finish issue' => 'Terminer tâche',
    'Finished at' => 'Terminé le',
    'From this time recommended begin to start work' => 'Date à laquelle il est recommandé de travailler',
    'Has not deadline' => 'Pas de date limite',
    'More details, please...' => 'Plus de détail svp...',
    'Must be completed by' => 'Doit être terminé par',
    'Name' => 'Nom',
    'New issue' => 'Nouvelle tâche',
    'No open issues...' => 'Pas de tâche ouverte',
    'Notify assignors' => 'Notifier les personnes',
    'Owner' => 'Propriétaire',
    'Priority' => 'Priorité',
    'Save' => 'Sauver',
    'Select a space in which the new issue will be added. If nothing is selected, the task will be attached to your profile.' => 'Choisir un projet où la tâche sera ajoutée. Si vous ne spécifiez rien, la tâche sera ajoutée à votre profil.',
    'Select assignees' => 'Définir exécutants',
    'Started Date' => 'Date de début',
    'Started Time' => 'Heure de début',
    'Started at' => 'Démarré à',
    'Status' => 'Statut',
    'Tags' => 'Tags',
    'Text Color' => 'Couleur texte',
    'The planned time by which you should end work.' => 'La date à laquelle vous devriez avoir terminé',
    'This issue has subtasks' => 'La tâche a des sous-tâches',
    'This issue is subtask for the issue' => 'La tâche est une sous-tâche de cette tâche',
    'This list of personal tags. It is can be a tag, a milestone, label or other that you can mark a issue. This tags visible only for you.' => 'La liste des tags personnels. Cela peut être un tag, une mention ou autre chose qui vous permet de définir la nature d&quot;une tâche',
    'Timeline' => 'Ligne du temps',
    'Title' => 'Titre',
    'Validity period' => 'Période de validité',
    'Visibility' => 'Visibilité',
    'What is to do?' => 'Titre de votre tâche ?',
    'constantly' => 'Constante',
    'from' => 'De',
    'to' => 'à',
    '{userName} assigned you to the issue {issue}.' => '{userName} vous a assigné la tâche {issue}.',
    '{userName} changed the issue {issue} wherever you are assigned.' => '{userName} a changé la tâche {issue} où vosu étiez assigné.',
];
