<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Designate</strong> tag to issue' => '',
    'Add' => '',
    'Add Subtask' => '',
    'Adopted' => '',
    'Adopted at' => '',
    'Are you sure you want to delete this item?' => '',
    'Assigned Users' => '',
    'Assigned at' => '',
    'Assignee' => '',
    'Background Color' => '',
    'Calendar' => '',
    'Create Tag' => '',
    'Date' => '',
    'Deadline' => '',
    'Deadline Date' => '',
    'Deadline Time' => '',
    'Description' => '',
    'Designate tag' => '',
    'Done' => '',
    'Finish issue' => '',
    'Finished at' => '',
    'From this time recommended begin to start work' => '',
    'Has not deadline' => '',
    'More details, please...' => '',
    'Must be completed by' => '',
    'Name' => '',
    'New issue' => '',
    'No open issues...' => '',
    'Notify assignors' => '',
    'Owner' => '',
    'Priority' => '',
    'Save' => '',
    'Select a space in which the new issue will be added. If nothing is selected, the task will be attached to your profile.' => '',
    'Select assignees' => '',
    'Started Date' => '',
    'Started Time' => '',
    'Started at' => '',
    'Status' => '',
    'Tags' => '',
    'Text Color' => '',
    'The planned time by which you should end work.' => '',
    'This issue has subtasks' => '',
    'This issue is subtask for the issue' => '',
    'This list of personal tags. It is can be a tag, a milestone, label or other that you can mark a issue. This tags visible only for you.' => '',
    'Timeline' => '',
    'Title' => '',
    'Visibility' => '',
    'What is to do?' => '',
    '{userName} assigned you to the issue {issue}.' => '',
    '{userName} changed the issue {issue} wherever you are assigned.' => '',
];
